apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tektutor-springboot-microservice 
  labels:
    app: springms 
spec:
  source:
    type: Git
    git:
      uri: https://github.com/tektutor/openshift-feb-2024.git
    contextDir: Day5/DevfileAndDeployDemo/spring-ms 
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile 
  output:
    to:
      kind: ImageStreamTag
      name: tektutor-spring-microservice:latest
