apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: tektutor-spring-microservice:2.0 
        imagePullPolicy: IfNotPresent
        name: spring-ms
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-v2
spec:
  ports:
  - port: 8080
    protocol: TCP 
    targetPort: 8080
  selector:
    app: hello
