apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.127 # Replace this IP with 10.10.15.61 or 10.10.15.62 or 10.10.15.63 depending on your linux user 
    path: /var/nfs/jegan/mysql # Replace this path with /var/nfs/user01/share2 folder
