apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk 
            operator: In
            values:
            - ssd
  containers:
  - image: tektutor/spring-tektutor-helloms:latest
    name: hello
