apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.mysqlPVName }} 
  labels:
    name: {{ .Values.yourProjectName }} 
spec:
  capacity:
    storage: {{ .Values.pv.mysqlPVSize }} 
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.serverIP }} 
    path: {{ .Values.nfs.mysqlNFSPath }}
