apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql

spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.mysqlPVCName }} 

      containers:
      - name: mysql
        image: bitnami/mariadb:latest
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: mysql-storage
          mountPath: /bitnami/mariadb/data

        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: password

        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-cm
              key: database
