apiVersion: v1
kind: Pod 
metadata:
  name: hello-pod
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: ubuntu:latest 
        command: ["sh", "-c", "echo 'Hello Job Started' && sleep 20 && exit 0"]
      restartPolicy: Never
