apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
    pod-template-hash: rs 
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: rs 
  template:
    metadata:
      labels:
        app: nginx
        pod-template-hash: rs 
    spec:
      containers:
      - image: bitnami/nginx:latest
        name: nginx
